#pragma once

#include "Common.hpp"

/* 
*  GLFW key codes mapped into own code system. 
*/

#define THR_KEY_SPACE              GLFW_KEY_SPACE              
#define THR_KEY_APOSTROPHE         GLFW_KEY_APOSTROPHE         
#define THR_KEY_COMMA              GLFW_KEY_COMMA              
#define THR_KEY_MINUS              GLFW_KEY_MINUS              
#define THR_KEY_PERIOD             GLFW_KEY_PERIOD             
#define THR_KEY_SLASH              GLFW_KEY_SLASH              
#define THR_KEY_0                  GLFW_KEY_0                  
#define THR_KEY_1                  GLFW_KEY_1                  
#define THR_KEY_2                  GLFW_KEY_2                  
#define THR_KEY_3                  GLFW_KEY_3                  
#define THR_KEY_4                  GLFW_KEY_4                  
#define THR_KEY_5                  GLFW_KEY_5                  
#define THR_KEY_6                  GLFW_KEY_6                  
#define THR_KEY_7                  GLFW_KEY_7                  
#define THR_KEY_8                  GLFW_KEY_8                  
#define THR_KEY_9                  GLFW_KEY_9                  
#define THR_KEY_SEMICOLON          GLFW_KEY_SEMICOLON          
#define THR_KEY_EQUAL              GLFW_KEY_EQUAL              
#define THR_KEY_A                  GLFW_KEY_A                  
#define THR_KEY_B                  GLFW_KEY_B                  
#define THR_KEY_C                  GLFW_KEY_C                  
#define THR_KEY_D                  GLFW_KEY_D                  
#define THR_KEY_E                  GLFW_KEY_E                  
#define THR_KEY_F                  GLFW_KEY_F                  
#define THR_KEY_G                  GLFW_KEY_G                  
#define THR_KEY_H                  GLFW_KEY_H                  
#define THR_KEY_I                  GLFW_KEY_I                  
#define THR_KEY_J                  GLFW_KEY_J                  
#define THR_KEY_K                  GLFW_KEY_K                  
#define THR_KEY_L                  GLFW_KEY_L                  
#define THR_KEY_M                  GLFW_KEY_M                  
#define THR_KEY_N                  GLFW_KEY_N                  
#define THR_KEY_O                  GLFW_KEY_O                  
#define THR_KEY_P                  GLFW_KEY_P                  
#define THR_KEY_Q                  GLFW_KEY_Q                  
#define THR_KEY_R                  GLFW_KEY_R                  
#define THR_KEY_S                  GLFW_KEY_S                  
#define THR_KEY_T                  GLFW_KEY_T                  
#define THR_KEY_U                  GLFW_KEY_U                  
#define THR_KEY_V                  GLFW_KEY_V                  
#define THR_KEY_W                  GLFW_KEY_W                  
#define THR_KEY_X                  GLFW_KEY_X                  
#define THR_KEY_Y                  GLFW_KEY_Y                  
#define THR_KEY_Z                  GLFW_KEY_Z                  
#define THR_KEY_LEFT_BRACKET       GLFW_KEY_LEFT_BRACKET       
#define THR_KEY_BACKSLASH          GLFW_KEY_BACKSLASH          
#define THR_KEY_RIGHT_BRACKET      GLFW_KEY_RIGHT_BRACKET      
#define THR_KEY_GRAVE_ACCENT       GLFW_KEY_GRAVE_ACCENT       
#define THR_KEY_WORLD_1            GLFW_KEY_WORLD_1            
#define THR_KEY_WORLD_2            GLFW_KEY_WORLD_2            

#define THR_KEY_ESCAPE             GLFW_KEY_ESCAPE             
#define THR_KEY_ENTER              GLFW_KEY_ENTER              
#define THR_KEY_TAB                GLFW_KEY_TAB                
#define THR_KEY_BACKSPACE          GLFW_KEY_BACKSPACE          
#define THR_KEY_INSERT             GLFW_KEY_INSERT             
#define THR_KEY_DELETE             GLFW_KEY_DELETE             
#define THR_KEY_RIGHT              GLFW_KEY_RIGHT              
#define THR_KEY_LEFT               GLFW_KEY_LEFT               
#define THR_KEY_DOWN               GLFW_KEY_DOWN               
#define THR_KEY_UP                 GLFW_KEY_UP                 
#define THR_KEY_PAGE_UP            GLFW_KEY_PAGE_UP            
#define THR_KEY_PAGE_DOWN          GLFW_KEY_PAGE_DOWN          
#define THR_KEY_HOME               GLFW_KEY_HOME               
#define THR_KEY_END                GLFW_KEY_END                
#define THR_KEY_CAPS_LOCK          GLFW_KEY_CAPS_LOCK          
#define THR_KEY_SCROLL_LOCK        GLFW_KEY_SCROLL_LOCK        
#define THR_KEY_NUM_LOCK           GLFW_KEY_NUM_LOCK           
#define THR_KEY_PRINT_SCREEN       GLFW_KEY_PRINT_SCREEN       
#define THR_KEY_PAUSE              GLFW_KEY_PAUSE              
#define THR_KEY_F1                 GLFW_KEY_F1                 
#define THR_KEY_F2                 GLFW_KEY_F2                 
#define THR_KEY_F3                 GLFW_KEY_F3                 
#define THR_KEY_F4                 GLFW_KEY_F4                 
#define THR_KEY_F5                 GLFW_KEY_F5                 
#define THR_KEY_F6                 GLFW_KEY_F6                 
#define THR_KEY_F7                 GLFW_KEY_F7                 
#define THR_KEY_F8                 GLFW_KEY_F8                 
#define THR_KEY_F9                 GLFW_KEY_F9                 
#define THR_KEY_F10                GLFW_KEY_F10                
#define THR_KEY_F11                GLFW_KEY_F11                
#define THR_KEY_F12                GLFW_KEY_F12                
#define THR_KEY_F13                GLFW_KEY_F13                
#define THR_KEY_F14                GLFW_KEY_F14                
#define THR_KEY_F15                GLFW_KEY_F15                
#define THR_KEY_F16                GLFW_KEY_F16                
#define THR_KEY_F17                GLFW_KEY_F17                
#define THR_KEY_F18                GLFW_KEY_F18                
#define THR_KEY_F19                GLFW_KEY_F19                
#define THR_KEY_F20                GLFW_KEY_F20                
#define THR_KEY_F21                GLFW_KEY_F21                
#define THR_KEY_F22                GLFW_KEY_F22                
#define THR_KEY_F23                GLFW_KEY_F23                
#define THR_KEY_F24                GLFW_KEY_F24                
#define THR_KEY_F25                GLFW_KEY_F25                
#define THR_KEY_KP_0               GLFW_KEY_KP_0               
#define THR_KEY_KP_1               GLFW_KEY_KP_1               
#define THR_KEY_KP_2               GLFW_KEY_KP_2               
#define THR_KEY_KP_3               GLFW_KEY_KP_3               
#define THR_KEY_KP_4               GLFW_KEY_KP_4               
#define THR_KEY_KP_5               GLFW_KEY_KP_5               
#define THR_KEY_KP_6               GLFW_KEY_KP_6               
#define THR_KEY_KP_7               GLFW_KEY_KP_7               
#define THR_KEY_KP_8               GLFW_KEY_KP_8               
#define THR_KEY_KP_9               GLFW_KEY_KP_9               
#define THR_KEY_KP_DECIMAL         GLFW_KEY_KP_DECIMAL         
#define THR_KEY_KP_DIVIDE          GLFW_KEY_KP_DIVIDE          
#define THR_KEY_KP_MULTIPLY        GLFW_KEY_KP_MULTIPLY        
#define THR_KEY_KP_SUBTRACT        GLFW_KEY_KP_SUBTRACT        
#define THR_KEY_KP_ADD             GLFW_KEY_KP_ADD             
#define THR_KEY_KP_ENTER           GLFW_KEY_KP_ENTER           
#define THR_KEY_KP_EQUAL           GLFW_KEY_KP_EQUAL           
#define THR_KEY_LEFT_SHIFT         GLFW_KEY_LEFT_SHIFT         
#define THR_KEY_LEFT_CONTROL       GLFW_KEY_LEFT_CONTROL       
#define THR_KEY_LEFT_ALT           GLFW_KEY_LEFT_ALT           
#define THR_KEY_LEFT_SUPER         GLFW_KEY_LEFT_SUPER         
#define THR_KEY_RIGHT_SHIFT        GLFW_KEY_RIGHT_SHIFT        
#define THR_KEY_RIGHT_CONTROL      GLFW_KEY_RIGHT_CONTROL      
#define THR_KEY_RIGHT_ALT          GLFW_KEY_RIGHT_ALT          
#define THR_KEY_RIGHT_SUPER        GLFW_KEY_RIGHT_SUPER        
#define THR_KEY_MENU               GLFW_KEY_MENU               

#define THR_MOD_SHIFT              GLFW_MOD_SHIFT              
#define THR_MOD_CONTROL            GLFW_MOD_CONTROL            
#define THR_MOD_ALT                GLFW_MOD_ALT                
#define THR_MOD_SUPER              GLFW_MOD_SUPER              
#define THR_MOD_CAPS_LOCK          GLFW_MOD_CAPS_LOCK          
#define THR_MOD_NUM_LOCK           GLFW_MOD_NUM_LOCK           

#define THR_MOUSE_BUTTON_1         GLFW_MOUSE_BUTTON_1        
#define THR_MOUSE_BUTTON_2         GLFW_MOUSE_BUTTON_2        
#define THR_MOUSE_BUTTON_3         GLFW_MOUSE_BUTTON_3        
#define THR_MOUSE_BUTTON_4         GLFW_MOUSE_BUTTON_4        
#define THR_MOUSE_BUTTON_5         GLFW_MOUSE_BUTTON_5        
#define THR_MOUSE_BUTTON_6         GLFW_MOUSE_BUTTON_6        
#define THR_MOUSE_BUTTON_7         GLFW_MOUSE_BUTTON_7        
#define THR_MOUSE_BUTTON_8         GLFW_MOUSE_BUTTON_8        
#define THR_MOUSE_BUTTON_LAST      GLFW_MOUSE_BUTTON_LAST     
#define THR_MOUSE_BUTTON_LEFT      GLFW_MOUSE_BUTTON_LEFT     
#define THR_MOUSE_BUTTON_RIGHT     GLFW_MOUSE_BUTTON_RIGHT    
#define THR_MOUSE_BUTTON_MIDDLE    GLFW_MOUSE_BUTTON_MIDDLE   
